import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    // Sidebar
    dashboard: 'Dashboard',
    assistant: 'AI Assistant',
    appointments: 'Appointments',
    patients: 'Patients',
    doctors: 'Doctors',
    schedules: 'Schedules',
    notifications: 'Notifications',
    analytics: 'Analytics',
    monitoring: 'Monitoring',
    settings: 'Settings',
    needHelp: 'Need Help?',
    askAI: 'Ask AI Assistant',
    
    // Dashboard
    welcome: 'Welcome back, Admin 👋',
    totalAppointments: 'Total Appointments',
    noShow: 'No-Show',
    fromLastWeek: 'from last week',
    apptTrend: 'Appointment Trend',
    deptLoad: 'Department Wise Load',
    noShowPred: 'No-Show Prediction',
    upcomingAppts: 'Upcoming Appointments',
    todaysReminders: 'Today\'s Reminders',
    aiInsights: 'AI Insights',
    viewAll: 'View All',
    newAppt: 'New Appointment',
    
    // AI Assistant
    aiAssistantTitle: 'AI Appointment Assistant',
    welcomeAssistant: 'Hello! I\'m your AI Appointment Assistant. I can help you book appointments, manage schedules, check patient records, and more. How can I help you today?',
    chatCleared: 'Chat cleared. How can I help you today?',
    online: 'Online',
    clearChat: 'Clear Chat',
    typeMessage: 'Type your message...',
    quickStats: 'Quick Stats',
    capabilities: 'AI Capabilities',
    aiTip: 'AI Tip',
    assistantGoal1: 'Booking and managing medical appointments',
    assistantGoal2: 'Providing information about doctors, departments, and schedules',
    assistantGoal3: 'Checking patient histories and appointment statuses',
    assistantGoal4: 'Answering healthcare administrative questions',
    
    // Stats Keys
    totalappointments: 'Total Appointments',
    confirmed: 'Confirmed',
    cancelled: 'Cancelled',
    noshow: 'No-Show',
    walkins: 'Walk-ins',

    // Appointments Page
    manageAppts: 'Manage and view all appointments',
    aiBook: 'AI Book',
    totalToday: 'Total Today',
    pending: 'Pending',
    allAppts: 'All Appointments',
    today: 'Today',
    tomorrow: 'Tomorrow',
    thisWeek: 'This Week',
    thisMonth: 'This Month',
    searchPlaceholderAppts: 'Search appointments, patients, doctors...',
    filter: 'Filter',
    patient: 'Patient',
    doctor: 'Doctor',
    dateTime: 'Date & Time',
    type: 'Type',
    status: 'Status',
    action: 'Action',
    showing: 'Showing',
    of: 'of',
    
    // Patients Page
    managePatients: 'Manage and view all patient records',
    bookAppt: 'Book Appointment',
    addPatient: 'Add Patient',
    active: 'Active',
    critical: 'Critical',
    newThisMonth: 'New This Month',
    searchPlaceholderPatients: 'Search patients by name or ID...',
    ageGender: 'Age / Gender',
    bloodType: 'Blood Type',
    condition: 'Condition',
    visits: 'Visits',
    actions: 'Actions',
    
    // Analytics Page
    analyticsTitle: 'Analytics',
    performanceInsights: 'Performance insights and business intelligence',
    export: 'Export',
    totalRevenue: 'Total Revenue (MTD)',
    avgDailyAppts: 'Avg Daily Appointments',
    noShowRate: 'No-Show Rate',
    patientSatisfaction: 'Patient Satisfaction',
    bookingCompletionRate: 'Booking Completion Rate',
    avgResponseTime: 'Avg Response Time',
    revenueTrends: 'Appointment & Revenue Trends',
    revenueByDept: 'Revenue by Department',
    noShowRiskTrend: 'No-Show Risk Trend',
    topDoctors: 'Top Performing Doctors',
    vsLastPeriod: 'vs last period',
    
    // Remaining Pages
    manageDoctors: 'Manage and view all medical staff',
    viewSchedules: 'View and manage doctor schedules',
    monitoringTitle: 'Health Monitoring',
    realTimeInsights: 'Real-time patient vitals and health data',
    settingsTitle: 'System Settings',
    configureApp: 'Configure application preferences and security',
    recentNotifications: 'Recent Notifications',
    manageAlerts: 'Manage system alerts and messages',
    
    // AI Assistant Appointment Card
    apptReadyTitle: 'Appointment Ready!',
    apptReadySub: 'Please confirm your appointment details.',
    date: 'Date',
    time: 'Time',
    location: 'Location',
    bookNowAI: 'Book Now via AI Flow',
    dataSecure: 'Your data is secure and protected',
    
    // Doctors Page
    addDoctor: 'Add Doctor',
    searchPlaceholderDoctors: 'Search doctors...',
    
    // AI Assistant Messages
    extractingDetails: 'Extracting appointment details...',
    errorResponse: 'Sorry, I could not process that.',
    errorOccurred: 'I encountered an error. Please try again.',
    bookingConfirmedMsg: 'Great! Your appointment has been confirmed with {doctor} on {date} at {time}. You will receive confirmation via SMS, Email, and WhatsApp.',
    bookingCancelledMsg: 'Booking cancelled. Let me know if you need help with anything else.',
    
    // Layout
    book: 'Book',
    searchPlaceholderGeneral: 'Search patients, appointments...',
    voiceSearch: 'Voice Search',
    
    // Quick Actions
    actionBook: 'Book appointment with cardiologist',
    actionSchedule: "Show today's schedule",
    actionHistory: "Check patient Rahul Joshi's history",
    actionHelp: 'What can you help me with?',
    actionLoad: 'Tell me about the hospital load',

    // Booking Flow
    bookAppointment: 'Book Appointment',
    aiBookingSub: 'AI-powered intelligent booking',
    selectLanguage: 'Select Language',
    symptoms: 'Symptoms',
    aiAnalysis: 'AI Analysis',
    selectDoctor: 'Select Doctor',
    dateAndTime: 'Date & Time',
    confirm: 'Confirm',
    describeSymptoms: 'Describe Your Symptoms',
    describeSymptomsSub: "Tell us how you're feeling and our AI will recommend the right department & doctor",
    symptomPlaceholder: "Describe your symptoms... e.g. 'I have been experiencing chest pain and shortness of breath for the past 2 days'",
    commonSymptoms: 'Common symptoms',
    analyzeWithAI: 'Analyze with AI',
    aiSymptomAnalysis: 'AI Symptom Analysis',
    aiSymptomAnalysisSub: 'Our NLP engine is processing your symptoms',
    analysisComplete: 'Analysis Complete',
    confidence: 'Confidence',
    recommendedDept: 'Recommended Department',
    urgencyLevel: 'Urgency Level',
    symptomsAnalyzed: 'Symptoms analyzed',
    changeDeptOptional: 'Change Department (optional)',
    back: 'Back',
    pickDateAndTime: 'Pick Date & Time',
    availableDoctorsIn: 'Available doctors in',
    notAvailable: 'Not available',
    onLeave: 'On Leave',
    slots: 'slots',
    chooseDate: 'Choose Date',
    availableTimeSlots: 'Available Time Slots',
    selectTimeHint: 'Please select a time slot to continue',
    reviewBooking: 'Review Booking',
    confirmAppointment: 'Confirm Appointment',
    reviewDetails: 'Please review your appointment details',
    remindersVia: "You'll receive reminders via",
    securityNote: 'Your booking is secured with end-to-end encryption',
    confirmBooking: 'Confirm Booking',
    confirming: 'Confirming...',
    bookingConfirmed: 'Booking Confirmed!',
    bookingSuccessMsg: 'Your appointment has been successfully booked',
    appointmentId: 'Appointment ID',
    confirmationSentMsg: 'Confirmation sent via SMS, Email & WhatsApp',
    highUrgency: 'High Urgency',
    mediumUrgency: 'Medium Urgency',
    lowUrgency: 'Low Urgency',
    sms: 'SMS',
    email: 'Email',
    whatsapp: 'WhatsApp',
    hospitalLocation: 'City Care Hospital, Main Street',
  },
  hi: {
    // Sidebar
    dashboard: 'डैशबोर्ड',
    assistant: 'एआई सहायक',
    appointments: 'नियुक्तियाँ',
    patients: 'मरीज',
    doctors: 'डॉक्टर',
    schedules: 'अनुसूची',
    notifications: 'सूचनाएं',
    analytics: 'विश्लेषण',
    monitoring: 'निगरानी',
    settings: 'सेटिंग्स',
    needHelp: 'क्या आपको मदद चाहिए?',
    askAI: 'एआई सहायक से पूछें',
    
    // Dashboard
    welcome: 'वापसी पर स्वागत है, एडमिन 👋',
    totalAppointments: 'कुल नियुक्तियाँ',
    noShow: 'नहीं आए',
    fromLastWeek: 'पिछले सप्ताह से',
    apptTrend: 'नियुक्ति की प्रवृत्ति',
    deptLoad: 'विभागवार लोड',
    noShowPred: 'नहीं आने की भविष्यवाणी',
    upcomingAppts: 'आने वाली नियुक्तियाँ',
    todaysReminders: 'आज के रिमाइंडर',
    aiInsights: 'एआई अंतर्दृष्टि',
    viewAll: 'सभी देखें',
    newAppt: 'नई नियुक्ति',
    
    // AI Assistant
    aiAssistantTitle: 'एआई नियुक्ति सहायक',
    welcomeAssistant: 'नमस्ते! मैं आपका एआई नियुक्ति सहायक हूँ। मैं नियुक्तियाँ बुक करने, कार्यक्रम प्रबंधित करने, मरीज के रिकॉर्ड जाँचने और बहुत कुछ करने में आपकी मदद कर सकता हूँ। मैं आज आपकी क्या मदद कर सकता हूँ?',
    chatCleared: 'चैट साफ हो गई। मैं आज आपकी क्या मदद कर सकता हूँ?',
    online: 'ऑनलाइन',
    clearChat: 'चैट साफ करें',
    typeMessage: 'अपना संदेश लिखें...',
    quickStats: 'त्वरित आँकड़े',
    capabilities: 'एआई क्षमताएं',
    aiTip: 'एआई टिप',
    assistantGoal1: 'चिकित्सा नियुक्तियों की बुकिंग और प्रबंधन',
    assistantGoal2: 'डॉक्टरों, विभागों और कार्यक्रमों के बारे में जानकारी प्रदान करना',
    assistantGoal3: 'मरीज के इतिहास और नियुक्ति की स्थिति की जांच करना',
    assistantGoal4: 'स्वास्थ्य सेवा प्रशासनिक प्रश्नों का उत्तर देना',

    // Stats Keys
    totalappointments: 'कुल नियुक्तियाँ',
    noshow: 'नहीं आए',

    // Appointments Page
    manageAppts: 'सभी नियुक्तियों को प्रबंधित करें और देखें',
    aiBook: 'एआई बुक',
    totalToday: 'आज कुल',
    pending: 'लंबित',
    allAppts: 'सभी नियुक्तियाँ',
    today: 'आज',
    tomorrow: 'कल',
    thisWeek: 'इस सप्ताह',
    thisMonth: 'इस महीने',
    searchPlaceholderAppts: 'नियुक्तियाँ, मरीज, डॉक्टर खोजें...',
    filter: 'फ़िल्टर',
    patient: 'मरीज',
    doctor: 'डॉक्टर',
    dateTime: 'दिनांक और समय',
    type: 'प्रकार',
    status: 'स्थिति',
    action: 'कार्रवाई',
    showing: 'दिखा रहे हैं',
    of: 'में से',

    // Patients Page
    managePatients: 'सभी मरीज रिकॉर्ड प्रबंधित करें और देखें',
    bookAppt: 'नियुक्ति बुक करें',
    addPatient: 'मरीज जोड़ें',
    active: 'सक्रिय',
    critical: 'गंभीर',
    newThisMonth: 'इस महीने नए',
    searchPlaceholderPatients: 'नाम या आईडी द्वारा मरीज खोजें...',
    ageGender: 'आयु / लिंग',
    bloodType: 'रक्त समूह',
    condition: 'स्थिति/बीमारी',
    visits: 'मुलाकातें',
    actions: 'कार्रवाई',

    // Analytics Page
    analyticsTitle: 'विश्लेषण',
    performanceInsights: 'प्रदर्शन अंतर्दृष्टि और व्यावसायिक बुद्धिमत्ता',
    export: 'निर्यात',
    totalRevenue: 'कुल राजस्व (MTD)',
    avgDailyAppts: 'औसत दैनिक नियुक्तियाँ',
    noShowRate: 'नहीं आने की दर',
    patientSatisfaction: 'मरीज संतुष्टि',
    bookingCompletionRate: 'बुकिंग पूर्णता दर',
    avgResponseTime: 'औसत प्रतिक्रिया समय',
    revenueTrends: 'नियुक्ति और राजस्व प्रवृत्तियाँ',
    revenueByDept: 'विभाग द्वारा राजस्व',
    noShowRiskTrend: 'नहीं आने के जोखिम की प्रवृत्ति',
    topDoctors: 'शीर्ष प्रदर्शन करने वाले डॉक्टर',
    vsLastPeriod: 'पिछली अवधि की तुलना में',

    // Remaining Pages
    manageDoctors: 'सभी चिकित्सा कर्मचारियों को प्रबंधित करें और देखें',
    viewSchedules: 'डॉक्टरों के कार्यक्रम देखें और प्रबंधित करें',
    monitoringTitle: 'स्वास्थ्य निगरानी',
    realTimeInsights: 'वास्तविक समय में मरीज की महत्वपूर्ण जानकारी और स्वास्थ्य डेटा',
    settingsTitle: 'सिस्टम सेटिंग्स',
    configureApp: 'एप्लिकेशन प्राथमिकताएं और सुरक्षा कॉन्फ़िगर करें',
    recentNotifications: 'हाल की सूचनाएं',
    manageAlerts: 'सिस्टम अलर्ट और संदेश प्रबंधित करें',

    // AI Assistant Appointment Card
    apptReadyTitle: 'नियुक्ति तैयार है!',
    apptReadySub: 'कृपया अपनी नियुक्ति के विवरण की पुष्टि करें।',
    date: 'दिनांक',
    time: 'समय',
    location: 'स्थान',
    bookNowAI: 'एआई फ्लो के माध्यम से अभी बुक करें',
    dataSecure: 'आपका डेटा सुरक्षित और सुरक्षित है',

    // Doctors Page
    addDoctor: 'डॉक्टर जोड़ें',
    searchPlaceholderDoctors: 'डॉक्टर खोजें...',

    // AI Assistant Messages
    extractingDetails: 'नियुक्ति विवरण निकाला जा रहा है...',
    errorResponse: 'क्षमा करें, मैं इसे संसाधित नहीं कर सका।',
    errorOccurred: 'मुझे एक त्रुटि मिली। कृपया पुन: प्रयास करें।',
    bookingConfirmedMsg: 'बहुत बढ़िया! {doctor} के साथ {date} को {time} बजे आपकी नियुक्ति की पुष्टि हो गई है। आपको एसएमएस, ईमेल और व्हाट्सएप के माध्यम से पुष्टि प्राप्त होगी।',
    bookingCancelledMsg: 'बुकिंग रद्द कर दी गई। मुझे बताएं कि क्या आपको किसी और चीज़ के लिए मदद चाहिए।',

    // Layout
    book: 'बुक करें',
    searchPlaceholderGeneral: 'मरीज, नियुक्तियाँ खोजें...',
    voiceSearch: 'आवाज खोज',

    // Quick Actions
    actionBook: 'कार्डियोलॉजिस्ट के साथ नियुक्ति बुक करें',
    actionSchedule: 'आज का शेड्यूल दिखाएं',
    actionHistory: 'मरीज राहुल जोशी का इतिहास जांचें',
    actionHelp: 'आप मेरी क्या मदद कर सकते हैं?',
    actionLoad: 'अस्पताल के लोड के बारे में बताएं',

    // Booking Flow
    bookAppointment: 'नियुक्ति बुक करें',
    aiBookingSub: 'एआई-संचालित बुद्धिमान बुकिंग',
    selectLanguage: 'भाषा चुनें',
    symptoms: 'लक्षण',
    aiAnalysis: 'एआई विश्लेषण',
    selectDoctor: 'डॉक्टर चुनें',
    dateAndTime: 'दिनांक और समय',
    confirm: 'पुष्टि करें',
    describeSymptoms: 'अपने लक्षणों का वर्णन करें',
    describeSymptomsSub: "हमें बताएं कि आप कैसा महसूस कर रहे हैं और हमारा एआई सही विभाग और डॉक्टर की सिफारिश करेगा",
    symptomPlaceholder: "अपने लक्षणों का वर्णन करें... जैसे 'मुझे पिछले 2 दिनों से सीने में दर्द और सांस लेने में तकलीफ हो रही है'",
    commonSymptoms: 'सामान्य लक्षण',
    analyzeWithAI: 'एआई के साथ विश्लेषण करें',
    aiSymptomAnalysis: 'एआई लक्षण विश्लेषण',
    aiSymptomAnalysisSub: 'हमारा एनएलपी इंजन आपके लक्षणों को संसाधित कर रहा है',
    analysisComplete: 'विश्लेषण पूरा हुआ',
    confidence: 'आत्मविश्वास',
    recommendedDept: 'अनुशंसित विभाग',
    urgencyLevel: 'अत्यावश्यकता स्तर',
    symptomsAnalyzed: 'लक्षणों का विश्लेषण किया गया',
    changeDeptOptional: 'विभाग बदलें (वैकल्पिक)',
    back: 'पीछे',
    pickDateAndTime: 'दिनांक और समय चुनें',
    availableDoctorsIn: 'उपलब्ध डॉक्टर',
    notAvailable: 'उपलब्ध नहीं',
    onLeave: 'छुट्टी पर',
    slots: 'स्लॉट',
    chooseDate: 'दिनांक चुनें',
    availableTimeSlots: 'उपलब्ध समय स्लॉट',
    selectTimeHint: 'जारी रखने के लिए कृपया एक समय स्लॉट चुनें',
    reviewBooking: 'बुकिंग की समीक्षा करें',
    confirmAppointment: 'नियुक्ति की पुष्टि करें',
    reviewDetails: 'कृपया अपनी नियुक्ति के विवरण की समीक्षा करें',
    remindersVia: "आपको इसके माध्यम से रिमाइंडर प्राप्त होंगे",
    securityNote: 'आपकी बुकिंग एंड-टू-एंड एन्क्रिप्शन के साथ सुरक्षित है',
    confirmBooking: 'बुकिंग की पुष्टि करें',
    confirming: 'पुष्टि हो रही है...',
    bookingConfirmed: 'बुकिंग की पुष्टि हो गई!',
    bookingSuccessMsg: 'आपकी नियुक्ति सफलतापूर्वक बुक कर ली गई है',
    appointmentId: 'नियुक्ति आईडी',
    confirmationSentMsg: 'एसएमएस, ईमेल और व्हाट्सएप के माध्यम से पुष्टि भेजी गई',
    highUrgency: 'उच्च अत्यावश्यकता',
    mediumUrgency: 'मध्यम अत्यावश्यकता',
    lowUrgency: 'कम अत्यावश्यकता',
    sms: 'एसएमएस',
    email: 'ईमेल',
    whatsapp: 'व्हाट्सएप',
    hospitalLocation: 'सिटी केयर हॉस्पिटल, मेन स्ट्रीट',
  },
  mr: {
    // Sidebar
    dashboard: 'डॅशबोर्ड',
    assistant: 'एआय सहाय्यक',
    appointments: 'अपॉइंटमेंट्स',
    patients: 'रुग्ण',
    doctors: 'डॉक्टर',
    schedules: 'वेळापत्रक',
    notifications: 'अधिसूचना',
    analytics: 'विश्लेषण',
    monitoring: 'देखरेख',
    settings: 'सेटिंग्ज',
    needHelp: 'मदत हवी आहे?',
    askAI: 'एआय सहाय्यकाला विचारा',
    
    // Dashboard
    welcome: 'पुन्हा स्वागत आहे, एडमिन 👋',
    totalAppointments: 'एकूण अपॉइंटमेंट्स',
    noShow: 'गैरहजर',
    fromLastWeek: 'मागच्या आठवड्यापासून',
    apptTrend: 'अपॉइंटमेंट ट्रेंड',
    deptLoad: 'विभागवार भार',
    noShowPred: 'गैरहजर राहण्याची शक्यता',
    upcomingAppts: 'येणाऱ्या अपॉइंटमेंट्स',
    todaysReminders: 'आजचे स्मरणपत्रे',
    aiInsights: 'एआय अंतर्दृष्टी',
    viewAll: 'सर्व पहा',
    newAppt: 'नवीन अपॉइंटमेंट',
    
    // AI Assistant
    aiAssistantTitle: 'एआय अपॉइंटमेंट सहाय्यक',
    welcomeAssistant: 'नमस्कार! मी तुमचा एआय अपॉइंटमेंट सहाय्यक आहे. मी तुम्हाला अपॉइंटमेंट बुक करण्यात, वेळापत्रक व्यवस्थापित करण्यात, रुग्णांच्या नोंदी तपासण्यात आणि बरेच काही करण्यात मदत करू शकतो. मी तुम्हाला आज कशी मदत करू शकतो?',
    chatCleared: 'चॅट साफ केले. मी तुम्हाला आज कशी मदत करू शकतो?',
    online: 'ऑनलाइन',
    clearChat: 'चॅट साफ करा',
    typeMessage: 'तुमचा संदेश टाइप करा...',
    quickStats: 'त्वरित आकडेवारी',
    capabilities: 'एआय क्षमता',
    aiTip: 'एआय टीप',
    assistantGoal1: 'वैद्यकीय अपॉइंटमेंट बुक करणे आणि व्यवस्थापित करणे',
    assistantGoal2: 'डॉक्टर, विभाग आणि वेळापत्रकांबद्दल माहिती प्रदान करणे',
    assistantGoal3: 'रुग्णांचा इतिहास आणि अपॉइंटमेंटची स्थिती तपासणे',
    assistantGoal4: 'आरोग्य सेवा प्रशासकीय प्रश्नांची उत्तरे देणे',

    // Stats Keys
    totalappointments: 'एकूण अपॉइंटमेंट्स',
    noshow: 'गैरहजर',

    // Appointments Page
    manageAppts: 'सर्व अपॉइंटमेंट्स व्यवस्थापित करा आणि पहा',
    aiBook: 'एआय बुक',
    totalToday: 'आजचे एकूण',
    pending: 'लंबित',
    allAppts: 'सर्व अपॉइंटमेंट्स',
    today: 'आज',
    tomorrow: 'उद्या',
    thisWeek: 'या आठवड्यात',
    thisMonth: 'या महिन्यात',
    searchPlaceholderAppts: 'अपॉइंटमेंट्स, रुग्ण, डॉक्टर शोधा...',
    filter: 'फिल्टर',
    patient: 'रुग्ण',
    doctor: 'डॉक्टर',
    dateTime: 'दिनांक आणि वेळ',
    type: 'प्रकार',
    status: 'स्थिती',
    action: 'कृती',
    showing: 'दाखवत आहे',
    of: 'पैकी',

    // Patients Page
    managePatients: 'सर्व रुग्ण नोंदी व्यवस्थापित करा आणि पहा',
    bookAppt: 'अपॉइंटमेंट बुक करा',
    addPatient: 'रुग्ण जोडा',
    active: 'सक्रिय',
    critical: 'गंभीर',
    newThisMonth: 'या महिन्यात नवीन',
    searchPlaceholderPatients: 'नाव किंवा आयडीनुसार रुग्ण शोधा...',
    ageGender: 'वय / लिंग',
    bloodType: 'रक्त गट',
    condition: 'स्थिती/आजार',
    visits: 'भेटी',
    actions: 'कृती',

    // Analytics Page
    analyticsTitle: 'विश्लेषण',
    performanceInsights: 'कामगिरी अंतर्दृष्टी आणि व्यवसाय बुद्धिमत्ता',
    export: 'निर्यात',
    totalRevenue: 'एकूण महसूल (MTD)',
    avgDailyAppts: 'सरासरी दररोजच्या अपॉइंटमेंट्स',
    noShowRate: 'गैरहजर राहण्याचे प्रमाण',
    patientSatisfaction: 'रुग्ण समाधान',
    bookingCompletionRate: 'बुकिंग पूर्ण होण्याचा दर',
    avgResponseTime: 'सरासरी प्रतिसाद वेळ',
    revenueTrends: 'अपॉइंटमेंट आणि महसूल ट्रेंड',
    revenueByDept: 'विभागानुसार महसूल',
    noShowRiskTrend: 'गैरहजर राहण्याच्या जोखमीचा ट्रेंड',
    topDoctors: 'उत्कृष्ट कामगिरी करणारे डॉक्टर',
    vsLastPeriod: 'मागील कालावधीच्या तुलनेत',

    // Remaining Pages
    manageDoctors: 'सर्व वैद्यकीय कर्मचाऱ्यांना व्यवस्थापित करा आणि पहा',
    viewSchedules: 'डॉक्टरांचे वेळापत्रक पहा आणि व्यवस्थापित करा',
    monitoringTitle: 'आरोग्य देखरेख',
    realTimeInsights: 'रिअल-टाइम रुग्णांचे महत्वाचे घटक आणि आरोग्य डेटा',
    settingsTitle: 'सिस्टम सेटिंग्ज',
    configureApp: 'अनुप्रयोग प्राधान्ये आणि सुरक्षा कॉन्फिगर करा',
    recentNotifications: 'अलीकडील अधिसूचना',
    manageAlerts: 'सिस्टम अलर्ट आणि संदेश व्यवस्थापित करा',

    // AI Assistant Appointment Card
    apptReadyTitle: 'अपॉइंटमेंट तयार आहे!',
    apptReadySub: 'कृपया आपल्या अपॉइंटमेंटच्या तपशीलांची पुष्टी करा.',
    date: 'दिनांक',
    time: 'वेळ',
    location: 'ठिकाण',
    bookNowAI: 'एआय फ्लोद्वारे आता बुक करा',
    dataSecure: 'तुमचा डेटा सुरक्षित आणि संरक्षित आहे',

    // Doctors Page
    addDoctor: 'डॉक्टर जोडा',
    searchPlaceholderDoctors: 'डॉक्टर शोधा...',

    // AI Assistant Messages
    extractingDetails: 'अपॉइंटमेंट तपशील काढले जात आहेत...',
    errorResponse: 'क्षमस्व, मी त्यावर प्रक्रिया करू शकलो नाही.',
    errorOccurred: 'मला एक त्रुटी आढळली. कृपया पुन्हा प्रयत्न करा.',
    bookingConfirmedMsg: 'उत्तम! {doctor} सोबत {date} रोजी {time} वाजता तुमची अपॉइंटमेंट निश्चित झाली आहे. तुम्हाला एसएमएस, ईमेल आणि व्हॉट्सॲपद्वारे पुष्टीकरण मिळेल.',
    bookingCancelledMsg: 'बुकिंग रद्द झाले. तुम्हाला इतर कशासाठी मदत हवी असल्यास मला कळवा.',

    // Layout
    book: 'बुक करा',
    searchPlaceholderGeneral: 'रुग्ण, अपॉइंटमेंट्स शोधा...',
    voiceSearch: 'आवाज शोध',

    // Quick Actions
    actionBook: 'कार्डिओलॉजिस्टसोबत अपॉइंटमेंट बुक करा',
    actionSchedule: 'आजचे वेळापत्रक दाखवा',
    actionHistory: 'रुग्ण राहुल जोशी यांचा इतिहास तपासा',
    actionHelp: 'तुम्ही मला काय मदत करू शकता?',
    actionLoad: 'हॉस्पिटलच्या लोडबद्दल सांगा',

    // Booking Flow
    bookAppointment: 'अपॉइंटमेंट बुक करा',
    aiBookingSub: 'एआय-आधारित इंटेलिजेंट बुकिंग',
    selectLanguage: 'भाषा निवडा',
    symptoms: 'लक्षणे',
    aiAnalysis: 'एआय विश्लेषण',
    selectDoctor: 'डॉक्टर निवडा',
    dateAndTime: 'दिनांक आणि वेळ',
    confirm: 'पुष्टी करा',
    describeSymptoms: 'तुमच्या लक्षणांचे वर्णन करा',
    describeSymptomsSub: "तुम्हाला कसे वाटत आहे ते आम्हाला सांगा आणि आमचे एआय योग्य विभाग आणि डॉक्टरांची शिफारस करेल",
    symptomPlaceholder: "तुमच्या लक्षणांचे वर्णन करा... उदा. 'मला गेल्या २ दिवसांपासून छातीत दुखत आहे आणि श्वास घेण्यास त्रास होत आहे'",
    commonSymptoms: 'सामान्य लक्षणे',
    analyzeWithAI: 'एआय सह विश्लेषण करा',
    aiSymptomAnalysis: 'एआय लक्षण विश्लेषण',
    aiSymptomAnalysisSub: 'आमचे एनएलपी इंजिन तुमच्या लक्षणांवर प्रक्रिया करत आहे',
    analysisComplete: 'विश्लेषण पूर्ण झाले',
    confidence: 'आत्मविश्वास',
    recommendedDept: 'शिफारस केलेला विभाग',
    urgencyLevel: 'तात्काळ पातळी',
    symptomsAnalyzed: 'विश्लेषण केलेली लक्षणे',
    changeDeptOptional: 'विभाग बदला (पर्यायी)',
    back: 'मागे',
    pickDateAndTime: 'दिनांक आणि वेळ निवडा',
    availableDoctorsIn: 'उपलब्ध डॉक्टर',
    notAvailable: 'उपलब्ध नाही',
    onLeave: 'रजेवर',
    slots: 'स्लॉट्स',
    chooseDate: 'दिनांक निवडा',
    availableTimeSlots: 'उपलब्ध वेळ स्लॉट्स',
    selectTimeHint: 'कृपया सुरू ठेवण्यासाठी वेळ स्लॉट निवडा',
    reviewBooking: 'बुकिंगचे पुनरावलोकन करा',
    confirmAppointment: 'अपॉइंटमेंटची पुष्टी करा',
    reviewDetails: 'कृपया आपल्या अपॉइंटमेंट तपशीलांचे पुनरावलोकन करा',
    remindersVia: "तुम्हाला याद्वारे स्मरणपत्रे मिळतील",
    securityNote: 'तुमचे बुकिंग एंड-टू-एंड एन्क्रिप्शनसह सुरक्षित आहे',
    confirmBooking: 'बुकिंगची पुष्टी करा',
    confirming: 'पुष्टी होत आहे...',
    bookingConfirmed: 'बुकिंग पुष्टी झाली!',
    bookingSuccessMsg: 'तुमची अपॉइंटमेंट यशस्वीरित्या बुक झाली आहे',
    appointmentId: 'अपॉइंटमेंट आयडी',
    confirmationSentMsg: 'एसएमएस, ईमेल आणि व्हॉट्सॲपद्वारे पुष्टीकरण पाठवले',
    highUrgency: 'उच्च निकड',
    mediumUrgency: 'मध्यम निकड',
    lowUrgency: 'कमी निकड',
    sms: 'एसएमएस',
    email: 'ईमेल',
    whatsapp: 'व्हॉट्सॲप',
    hospitalLocation: 'सिटी केअर हॉस्पिटल, मेन स्ट्रीट',
  }
};

export const LanguageProvider = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState('en');

  const t = (key) => {
    return translations[currentLanguage][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ currentLanguage, setCurrentLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
